-- Generated by Oracle SQL Developer Data Modeler 18.3.0.268.1208
--   at:        2019-05-13 19:49:24 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE atrakcja (
    id_atrakcji              INTEGER NOT NULL,
    nazwa                    VARCHAR2(20),
    kategoria_id_kategorii   INTEGER NOT NULL
);

ALTER TABLE atrakcja ADD CONSTRAINT atrakcja_pk PRIMARY KEY ( id_atrakcji );

CREATE TABLE czas (
    id_czasu   INTEGER NOT NULL,
    data       DATE
);

ALTER TABLE czas ADD CONSTRAINT czas_pk PRIMARY KEY ( id_czasu );

CREATE TABLE kategoria (
    id_kategorii   INTEGER NOT NULL,
    wiek_od        INTEGER,
    wzrost_od      INTEGER
);

ALTER TABLE kategoria ADD CONSTRAINT kategoria_pk PRIMARY KEY ( id_kategorii );

CREATE TABLE klient (
    id_klienta   INTEGER NOT NULL,
    imie         VARCHAR2(30),
    nazwisko     VARCHAR2(30),
    wiek         INTEGER,
    plec         VARCHAR2(15),
    wzrost       INTEGER
);

ALTER TABLE klient ADD CONSTRAINT klient_pk PRIMARY KEY ( id_klienta );

CREATE TABLE kraj (
    id_kraju      INTEGER NOT NULL,
    nazwa_kraju   VARCHAR2(30)
);

ALTER TABLE kraj ADD CONSTRAINT kraj_pk PRIMARY KEY ( id_kraju );

CREATE TABLE obszar (
    województwo_id_wojewodztwa   INTEGER NOT NULL,
    id_obszaru                   INTEGER NOT NULL,
    nazwa_miasta                 VARCHAR2(30)
);

ALTER TABLE obszar ADD CONSTRAINT obszar_pk PRIMARY KEY ( id_obszaru );

CREATE TABLE platnosc (
    id_platnosc   INTEGER NOT NULL,
    nazwa         VARCHAR2(15)
);

ALTER TABLE platnosc ADD CONSTRAINT platnosc_pk PRIMARY KEY ( id_platnosc );

CREATE TABLE sprzeda¿biletów (
    klient_id_klienta      INTEGER NOT NULL,
    obszar_id_obszaru      INTEGER NOT NULL,
    czas_id_czasu          INTEGER NOT NULL,
    atrakcja_id_atrakcji   INTEGER NOT NULL,
    ilosc                  INTEGER,
    cena                   NUMBER,
    platnosc_id_platnosc   INTEGER NOT NULL
);

ALTER TABLE sprzeda¿biletów
    ADD CONSTRAINT sprzeda¿biletów_pk PRIMARY KEY ( klient_id_klienta,
                                                    czas_id_czasu,
                                                    obszar_id_obszaru,
                                                    atrakcja_id_atrakcji,
                                                    platnosc_id_platnosc );

CREATE TABLE województwo (
    kraj_id_kraju       INTEGER NOT NULL,
    id_wojewodztwa      INTEGER NOT NULL,
    nazwa_wojewodztwa   VARCHAR2(30)
);

ALTER TABLE województwo ADD CONSTRAINT województwo_pk PRIMARY KEY ( id_wojewodztwa );

ALTER TABLE atrakcja
    ADD CONSTRAINT atrakcja_kategoria_fk FOREIGN KEY ( kategoria_id_kategorii )
        REFERENCES kategoria ( id_kategorii );

ALTER TABLE obszar
    ADD CONSTRAINT obszar_województwo_fk FOREIGN KEY ( województwo_id_wojewodztwa )
        REFERENCES województwo ( id_wojewodztwa );

ALTER TABLE sprzeda¿biletów
    ADD CONSTRAINT sprzeda¿biletów_atrakcja_fk FOREIGN KEY ( atrakcja_id_atrakcji )
        REFERENCES atrakcja ( id_atrakcji );

ALTER TABLE sprzeda¿biletów
    ADD CONSTRAINT sprzeda¿biletów_czas_fk FOREIGN KEY ( czas_id_czasu )
        REFERENCES czas ( id_czasu );

ALTER TABLE sprzeda¿biletów
    ADD CONSTRAINT sprzeda¿biletów_klient_fk FOREIGN KEY ( klient_id_klienta )
        REFERENCES klient ( id_klienta );

ALTER TABLE sprzeda¿biletów
    ADD CONSTRAINT sprzeda¿biletów_obszar_fk FOREIGN KEY ( obszar_id_obszaru )
        REFERENCES obszar ( id_obszaru );

ALTER TABLE sprzeda¿biletów
    ADD CONSTRAINT sprzeda¿biletów_platnosc_fk FOREIGN KEY ( platnosc_id_platnosc )
        REFERENCES platnosc ( id_platnosc );

ALTER TABLE województwo
    ADD CONSTRAINT województwo_kraj_fk FOREIGN KEY ( kraj_id_kraju )
        REFERENCES kraj ( id_kraju );

ALTER TABLE atrakcja
    ADD CONSTRAINT atrakcja_kategoria_fk FOREIGN KEY ( kategoria_id_kategorii )
        REFERENCES kategoria ( id_kategorii );

ALTER TABLE obszar
    ADD CONSTRAINT obszar_województwo_fk FOREIGN KEY ( województwo_id_wojewodztwa )
        REFERENCES województwo ( id_wojewodztwa );

ALTER TABLE sprzeda¿biletów
    ADD CONSTRAINT sprzeda¿biletów_atrakcja_fk FOREIGN KEY ( atrakcja_id_atrakcji )
        REFERENCES atrakcja ( id_atrakcji );

ALTER TABLE sprzeda¿biletów
    ADD CONSTRAINT sprzeda¿biletów_czas_fk FOREIGN KEY ( czas_id_czasu )
        REFERENCES czas ( id_czasu );

ALTER TABLE sprzeda¿biletów
    ADD CONSTRAINT sprzeda¿biletów_klient_fk FOREIGN KEY ( klient_id_klienta )
        REFERENCES klient ( id_klienta );

ALTER TABLE sprzeda¿biletów
    ADD CONSTRAINT sprzeda¿biletów_obszar_fk FOREIGN KEY ( obszar_id_obszaru )
        REFERENCES obszar ( id_obszaru );

ALTER TABLE sprzeda¿biletów
    ADD CONSTRAINT sprzeda¿biletów_platnosc_fk FOREIGN KEY ( platnosc_id_platnosc )
        REFERENCES platnosc ( id_platnosc );

ALTER TABLE województwo
    ADD CONSTRAINT województwo_kraj_fk FOREIGN KEY ( kraj_id_kraju )
        REFERENCES kraj ( id_kraju );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             25
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
